name: Some cursed problem matcher
description: Just messing about
author: meself
branding:
  icon: check-square
  color: purple

inputs:
  runtime-compile:
    description: "Compile the Rust script at runtime instead of using pre-built binary"
    type: boolean
    default: false
    required: false
  skip-directories:
    description: "Skip showing output from certain directories"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Rust binary
      if: ${{ inputs.runtime-compile == false || inputs.runtime-compile == 'false' }}
      shell: bash
      run: |
        echo "Running pre-built Rust binary"
        $GITHUB_ACTION_PATH/pre-built/main

    - name: Compile and run Rust script
      if: ${{ inputs.runtime-compile == true || inputs.runtime-compile == 'true' }}
      shell: bash
      run: |
        echo "Compiling with Rust nightly"
        cargo +nightly -Zscript ${{ github.action_path }}/main.rs
