name: Some cursed problem matcher
description: Just messing about
author: meself
branding:
  icon: check-square
  color: purple
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
  
    - name: Set Rust nightly
      run: |
        rustup override set nightly
        rustup --version
      shell: bash

    - name: Run Cargo script
      run: cargo +nightly -Zscript ${{ github.action_path }}main.rs
      shell: bash
