name: Build and push binary
on: workflow_dispatch

jobs:
  Build-and-push:
    name: Build and push binary
    runs-on: ubuntu-latest
    container:
      image: rust:bullseye
      options: --user 1001
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build
        shell: bash
        run: cargo +nightly build -Zscript -Zunstable-options --manifest-path $GITHUB_WORKSPACE/main.rs --artifact-dir $GITHUB_WORKSPACE/pre-built

      - name: Push
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add pre-built/main
          git commit -m "[Bot] Update pre-built binary"
          git push
