name: Build binary

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install crosstool-ng dependencies
        shell: bash
        run: sudo apt install build-essential help2man libtool-bin libtool-doc
          
      - name: Setup crosstool-ng
        shell: bash
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.29.0.tar.xz
          tar -xJf crosstool-ng-1.29.0.tar.xz
          cd crosstool-ng-1.29.0
          ./configure --enable-local
          make
          mkdir -p ./src
          wget -P ./src/ https://mirrors.edge.kernel.org/pub/linux/kernel/v3.x/linux-3.13.11.tar.xz
          ./ct-ng x86_64-ubuntu14.04-linux-gnu
          ./ct-ng build
          chmod u+w  $GITHUB_WORKSPACE/x86_64-ubuntu14.04-linux-gnu
    
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build
        shell: bash
        run: |
          cargo +nightly build -Zscript -Zunstable-options --manifest-path $GITHUB_WORKSPACE/main.rs --artifact-dir $GITHUB_WORKSPACE/artifact/
          objdump -T $GITHUB_WORKSPACE/artifact/main | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu

      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          path: artifact/main
          if-no-files-found: error
