name: Test Build on Linux

on: [push, pull_request]

jobs:
  Debian-Bullseye:
    runs-on: ubuntu-latest
    container:
      image: rust:bullseye

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: test
        shell: bash
        run: rustup toolchain install nightly-2026-08-27

      - name: Compile script
        shell: bash
        run: cargo ++nightly-2026-08-27 -Zscript ./main.rs
        env:
          GITHUB_ACTION_PATH: ${{ github.workspace }}
          RUSTFLAGS: "-Ztime-passes"

  Arch-Linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel

    steps:
      - name: Install Rust
        shell: bash
        run: sudo pacman -Syu --needed --noconfirm rustup

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Compile script
        shell: bash
        run: cargo +nightly -Zscript ./main.rs
        env:
          GITHUB_ACTION_PATH: ${{ github.workspace }}
          RUSTFLAGS: "-Ztime-passes"
