name: Test Build on Linux

on: [push, pull_request]

jobs:
  Debian-Bullseye:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Rust
        shell: bash
        run: rustup update

      - name: Build
        shell: bash
        run: cargo build --timings

      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          path: cargo-timings/cargo-timing.html
          if-no-files-found: error
          archive: false
